# shortcuts
abbr -a d     'docker'
abbr -a ghpr  'gh pr view --web'
abbr -a ghrp  'gh repo view --web'
abbr -a md    'mkdir -p'
abbr -a n     'nvim'
abbr -a off   'poweroff'
abbr -a py    'python3'
abbr -a t     'tmux'

# common directories
abbr -a -     'cd -'
abbr -a dow   'cd ~/Downloads'
abbr -a doc   'cd ~/Documents'

# git abbr
abbr -a g     'git'
abbr -a gs    'git stash'
abbr -a gsp   'git stash pop' 
abbr -a gl    'git pull'
abbr -a ga    'git add'
abbr -a gcm --set-cursor 'git commit -m "%"'
abbr -a gp    'git push'
abbr -a gcom  'git_checkout_main'
abbr -a gmom  'git_merge_origin_main'
abbr -a grh   'git_reset_hard'
abbr -a gco   'git checkout'
abbr -a gd    'git diff'
abbr -a grs   'git restore'
abbr -a gst   'git status'
abbr -a gsu   'git submodule update'
abbr -a gs    'git stash'
abbr -a gsp   'git stash pop'
abbr -a gclo  'git clone'
abbr -a glol  'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset"'
abbr -a gf    'git fetch'
abbr -a gcln  'git clean -fdx'
abbr -a gb    'git branch'
abbr -a gbs   'git branch --show-current'

# typo fixes
abbr -a suod  'sudo'
abbr -a nivm  'nvim'
abbr -a tumx  'tmux'
abbr -a clera 'clear'
