# shortcuts
abbr -a off   'poweroff'
abbr -a py    'python3'
abbr -a d     'docker'
abbr -a n     'nvim'
## git abbr
abbr -a g     'git'
abbr -a gs    'git stash'
abbr -a gsp   'git stash pop' 
abbr -a gl    'git pull'
abbr -a ga    'git add'
abbr -a gcm   'git commit -m'
abbr -a gp    'git push'
abbr -a gcom  'git_checkout_main'
abbr -a gmom  'git_merge_origin_main'
abbr -a gbc   'git branch --show-current'
abbr -a grh   'git_reset_hard'
abbr -a gco   'git checkout'
abbr -a gd    'git diff'
abbr -a grs   'git restore'
abbr -a gst   'git status'
abbr -a gsu   'git submodule update'

# typo fixes
abbr -a suod 'sudo'
abbr -a nivm 'nvim'
abbr -a tumx 'tmux'
abbr -a clera 'clear'
