 # General
  abbr --add d 'docker'
  abbr --add n 'nvim'
  abbr --add gs 'git stash'
  abbr --add gsp 'git stash pop'
  abbr --add suod 'sudo'
  abbr --add gal '~/custom_scripts/git_all'
  abbr --add saup 'sudo apt update'
  abbr --add saug 'sudo apt upgrade -y'
  abbr --add off 'poweroff'

  # Terminal colors (eza-based)
  abbr --add l 'eza -la'
  abbr --add lss 'eza -lf --color=always --sort=size'
  abbr --add ll 'eza -l --group-directories-first'
  abbr --add ld 'eza -lD'
  abbr --add lda 'eza -lDa'
  abbr --add lf 'eza -lf --color=always'
  abbr --add lfa 'eza -lfa --color=always'
  abbr --add lh 'eza -dl .* --group-directories-first'
  abbr --add lt 'eza -al --sort=modified'
