layerrule {
  name = Swaync control center blur
  blur_popups = on,
  ignore_alpha = 0.5
  match:namespace = swaync-control-center
} 

layerrule {
  name = Swaync notification popup blur
  blur_popups = on,
  ignore_alpha = 0.5
  match:namespace = swaync-notification-window
} 
